#!/bin/bash


# options to be displayed
option0="Administrator@fv.computerworks.ch"
option1="ComputerWorks@dev.computerworks.ch"

if [ -z $@ ]
then
    # Script gets called to get list of options.
    options="$option0\n$option1"
    printf $options;
else
    # Script gets called with chosen option. 
    chosen=$@;
    case $chosen in
        $option0)
            # nohup "screenshot_area_rofi" &>/dev/null & disown;;
            kitty zsh -c 'ssh Administrator@fv.computerworks.ch' &>/dev/null & disown;;
        $option1)
            # nohup "screenshot_area_rofi" &>/dev/null & disown;;
            kitty zsh -c 'ssh ComputerWorks@dev.computerworks.ch' &>/dev/null & disown;;
    esac
fi
