#!/bin/bash


# options to be displayed
option0="hibernate"
option1="reboot"
option2="shutdown"
option3="logout"

if [ -z $@ ]
then
    # Script gets called to get list of options.
    options="$option0\n$option1\n$option2\n$option3"
    printf $options;
else
    # Script gets called with chosen option. 
    chosen=$@;
    case $chosen in
        $option0)
            #nohup kitty zsh -c 'echo "blah"; exec zsh' &> /dev/null & disown;;  #zsh -c 'echo "test"'
            systemctl hibernate;;
        $option1)
            reboot;;
        $option2)
            shutdown -h now;;
        $option3)
            #nohup kitty zsh -c 'echo "blah"; exec zsh' &> /dev/null & disown;;  #zsh -c 'echo "test"'
            pkill -KILL -u $(whoami);;
    esac
fi
