#!/bin/bash


# options to be displayed
option_hibernate="hibernate"
option_reboot="reboot"
option_shutdown="shutdown"
option_logout="logout"
option_lock="lock"

if [ -z $@ ]
then
    # Script gets called to get list of options.
    options="\
$option_hibernate\n\
$option_reboot\n\
$option_shutdown\n\
$option_logout\n\
$option_lock\n"

    printf $options;
else
    # Script gets called with chosen option. 
    chosen=$@;
    case $chosen in
        $option_hibernate)
            #nohup kitty zsh -c 'echo "blah"; exec zsh' &> /dev/null & disown;;  #zsh -c 'echo "test"'
            systemctl hibernate;;
        $option_reboot)
            reboot;;
        $option_shutdown)
            shutdown -h now;;
        $option_logout)
            #nohup kitty zsh -c 'echo "blah"; exec zsh' &> /dev/null & disown;;  #zsh -c 'echo "test"'
            sudo systemctl restart ly;;
        $option_lock)
            slock &> /dev/null & disown;;
    esac
fi
