#!/bin/bash


# options to be displayed
option0="Upgrade"

if [ -z $@ ]
then
    # Script gets called to get list of options.
    options="$option0\n"
    printf $options;
else
    # Script gets called with chosen option. 
    chosen=$@;
    case $chosen in
        $option0)
            kitty fish -c 'system-upgrade; fish' &>/dev/null & disown;;
    esac
fi
