-- Configuration for outline.nvim (replacement for symbols-outline.nvim)
require("outline").setup({
  outline_window = {
    position = "right",
    width = 25,
    relative_width = true,
    auto_close = false,
    show_numbers = false,
    show_relative_numbers = false,
  },
  preview_window = {
    auto_preview = true,
  },
  symbol_folding = {
    auto_unfold_hover = true,
  },
  keymaps = {
    close = { "<Esc>", "q" },
    goto_location = "<Cr>",
    peek_location = "o",
    hover_symbol = "<C-space>",
    toggle_preview = "K",
    rename_symbol = "r",
    code_actions = "a",
  },
  symbols = {
    icons = {
      File = { icon = "", hl = "Identifier" },
      Module = { icon = "", hl = "@module" },
      Namespace = { icon = "", hl = "@namespace" },
      Package = { icon = "", hl = "@module" },
      Class = { icon = "𝓒", hl = "@type" },
      Method = { icon = "ƒ", hl = "@method" },
      Property = { icon = "", hl = "@property" },
      Field = { icon = "", hl = "@field" },
      Constructor = { icon = "", hl = "@constructor" },
      Enum = { icon = "ℰ", hl = "@type" },
      Interface = { icon = "ﰮ", hl = "@type" },
      Function = { icon = "", hl = "@function" },
      Variable = { icon = "", hl = "@variable" },
      Constant = { icon = "", hl = "@constant" },
      String = { icon = "𝓐", hl = "@string" },
      Number = { icon = "#", hl = "@number" },
      Boolean = { icon = "⊨", hl = "@boolean" },
      Array = { icon = "", hl = "@constant" },
      Object = { icon = "⦿", hl = "@type" },
      Key = { icon = "🔐", hl = "@type" },
      Null = { icon = "NULL", hl = "@type" },
      EnumMember = { icon = "", hl = "@field" },
      Struct = { icon = "𝓢", hl = "@structure" },
      Event = { icon = "🗲", hl = "@type" },
      Operator = { icon = "+", hl = "@operator" },
      TypeParameter = { icon = "𝙏", hl = "@parameter" },
    },
  },
})
