#!/bin/bash
TMPFILE="$(mktemp -t screencast-XXXXXXX).mkv"
echo "Tempfile is: "$TMPFILE
OUTPUT="$HOME/Pictures/Screencasts/$(date +%F-%H-%M-%S)"

RUNNING="$(pgrep -a ffmpeg | grep  "ffmpeg -f x11grab")"
if [ -z "$RUNNING" ]
then
    # Start recording process.

    read -r X Y W H G ID < <(slop -f "%x %y %w %h %g %i")
    ffmpeg -f x11grab -s "$W"x"$H" -i :0.0+$X,$Y "$TMPFILE"

    notify-send 'Generating palette'
    ffmpeg -y -i "$TMPFILE"  -vf fps=10,palettegen /tmp/palette.png
    notify-send 'Generating gif'
    ffmpeg -i "$TMPFILE" -i /tmp/palette.png -filter_complex "paletteuse" $OUTPUT.gif
    #mv $TMPFILE $OUTPUT.mkv

    notify-send "size $(du -h $OUTPUT.gif | awk '{print $1}')"

    #eog $OUTPUT.gif
    #trap "rm -f '$TMPFILE'" 0
    rm -f $TMPFILE
else
    # There is a record process running. kill it.
    # Get first word of that line, which is the pid of the process.
    PID="$(echo $RUNNING | awk '{print $1;}')"    
    kill $PID
fi

