#!/bin/bash

#read -p "Confirm sending mail [yes]: " response </dev/tty
response=$(kdialog --password "Confirm sending mail [yes]: ")
cmd="$*"

if [ "$response" == "yes" ]; then
    $cmd<&0
    exit
else
  echo "That's not a \"yes\"." 1>&2
  exit 1
fi
