#!/bin/bash

# Dependencies:
#  - kdialog

response=$(kdialog --inputbox "Confirm sending mail [yes]: ")
#echo $response
#read -p "Confirm sending mail [yes]: " response < /dev/tty
cmd="$*"

if [ "$response" == "yes" ]; then
    $cmd<&0
    exit
else
  echo "That's not a \"yes\"." 1>&2
  exit 1
fi
