#!/bin/bash

# Usage: conv-win-links WIN_LINK_FILE SYMLINK_FILE

# Obsolete root of link including \
LINKROOT=\\\\\\\\fsemu18.edu.ds.fhnw.ch\\\\e_18_data11\\\$\\\\
REALROOT=/mnt/fhnw_ad/HT/

LINKPATH=$(strings "$1" | grep $LINKROOT)
CLEANED=$(echo $LINKPATH | grep -oP "^$LINKROOT\K.*")
# Substitue backslashes with forward slashes
SUBST=${CLEANED//\\//}
ACTUALTARGET="$REALROOT$SUBST"

ln -s $ACTUALTARGET $2
