#!/bin/bash

# Usage: fhnw-sync [ diff ]
# fhnw-sync diff: Show difference between the files

SOURCE_PATH=$HOME"/OneDrive/Studium cloud"
TARGET_PATH=$HOME"/Documents/studium-module"
EXCLUDE_PATTERN="*.ova"


ARG=$1
sync_folder() {
	foldername=$(echo $1 | rev | cut -d "/" -f2 | rev)
	mkdir -p "$TARGET_PATH/$foldername"
	targetname="$TARGET_PATH/$foldername/mirror"
	cloudpath=${1%/*}
	cloudlink="$TARGET_PATH/$foldername/cloud"
	rm -rf $cloudlink
	ln -s "$cloudpath" "$cloudlink"
	mkdir -p "$targetname"
	# Previously used: rsync -r --info=progress2 symlink/ ~/Documents/fhnw_ad_mirror/itsm/

	if [ "$ARG" = "diff" ]
	then
		echo "============== DIFF FOR $foldername =============="
		rsync -rtmi --delete --dry-run --exclude=$EXCLUDE_PATTERN "$1/" "$targetname/"
	elif [ -z "$ARG" ]
	then
		echo "============== SYNCING $foldername =============="
		rsync -rtm --info=progress2 --delete --exclude=$EXCLUDE_PATTERN "$1/" "$targetname/"
	else
		echo "Unknown command"
		echo $1" -> "$targetname
	fi

	#rsync -rtm --info=progress2 --delete
}

ls -d -1 "$SOURCE_PATH/"*/symlink |
while read -r a;
	do sync_folder "$a";
done
