#!/bin/bash

# Old way which just gets the highest workspace index + 1
#i3-msg workspace $(($(i3-msg -t get_workspaces | tr , '\n' | grep '"num":' | cut -d : -f 2 | sort -rn | head -1) + 1))

# Lines with extra zero added last
WORKSPACENRS=$(i3-msg -t get_workspaces | tr , '\n' | grep '"num":' | cut -d : -f 2 | sort -n)$'\n'0
COUNT=1
RESULTNR=1

# Iterate through list of workspace (plus zero at the end), compare with sequential array of numbers, pick first number of those that doesn't match the input array.
while IFS= read -r line;do
    if [ "$COUNT" -ne "$line" ];then
        if [ "$COUNT" -gt "$line" ]; then
            # When number increased by more than it should, meaning there's a gap
            break
        fi
        # If previous number was repeated (so that it's less than the increased counter), do nothing.
    else
        # When number matched the previous + 1 exactly
        COUNT=$((COUNT + 1))
    fi
    RESULTNR=$COUNT
done <<< "$WORKSPACENRS"
echo $RESULTNR

