#!/bin/bash
# Obtain current workspace number
#CURRENT_WORKSPACE=$(i3-msg -t get_workspaces | jq '.[] | select(.focused==true).name' | cut -d : -f 1 | cut -d "\"" -f2)
#CURRENT_WORKSPACE=$(i3-msg -t get_workspaces | jq '.[] | select(.focused==true).name' | cut -d "\"" -f2)

i3-msg move container to workspace 300

