#!/bin/bash

# Path where to save the screenshot
SCREENSHOT_PATH=$HOME/Pictures/Screenshots
# How to format screenshot filename
SCREENSHOT_FORMAT='%Y-%m-%d@%H.%M.%S__'$HOSTNAME'.jpg'
# Milliseconds notification should be visible
NOTIFICATION_TIME=5000

mkdir -p $SCREENSHOT_PATH;
scrot -fsz -q 90 -l style=solid,width=2 $SCREENSHOT_PATH/$SCREENSHOT_FORMAT --exec 'xclip -selection c -t image/jpg < $f' && notify-send -u low -t $NOTIFICATION_TIME 'Scrot' 'Captured area screenshot and saved to clipboard (JPG, 90).'
