#!/bin/bash
# Path where to save the screenshot
SCREENSHOT_PATH=$HOME/Pictures/Screenshots
# How to format screenshot filename
SCREENSHOT_FORMAT='%Y-%m-%d@%H.%M.%S__'$HOSTNAME'.png'
# Milliseconds notification should be visible
NOTIFICATION_TIME=5000

mkdir -p $SCREENSHOT_PATH;
scrot -z -q 100 -l style=solid,width=2 $SCREENSHOT_PATH/$SCREENSHOT_FORMAT --exec 'xclip -selection c -t image/jpg < $f' && notify-send -u low -t $NOTIFICATION_TIME 'Scrot' 'Captured HQ fullscreen screenshot and saved to clipboard (PNG, 100).'
