#!/bin/bash

FULL_PATH=$(realpath $1)
NAME=$(echo $FULL_PATH | rev | cut -d "/" -f1 | rev)
echo $FULL_PATH
echo $NAME
7z a -t7z -mx=9 -mfb=273 -ms -md=31 -myx=9 -mtm=- -mmt -mmtf -md=1536m -mmf=bt3 -mmc=10000 -mpb=0 -mlc=0 "$NAME.7z" "$FULL_PATH/"
